### Lectura de datos y ajustes

In [105]:
# Leer librerías 

import numpy as np
import pandas as pd

In [131]:
# Cargar las bases y ajustar el tipo de datos

muestra = pd.read_csv('Data/muestra.csv')
votesper = pd.read_csv('Data/muestreo2_ajustado.csv')
votesper = votesper.astype({'PARROQUIA_CODIGO': str})
votesper

,PARROQUIA_CODIGO,Elección política,Votos por elección política,% de electores,Número de personas,Votos proporcionales
0,210752,Nulos,91.0,7.640638,17,1
1,210752,Blancos,122.0,10.243493,17,1
2,210752,Ausentes,140.0,11.754828,17,1
3,210752,10,0.0,0.000000,17,0
4,210752,1001,0.0,0.000000,17,0
...,...,...,...,...,...,...
13907,190750,83,0.0,0.000000,46,0
13908,190750,84,0.0,0.000000,46,0
13909,190750,85,0.0,0.000000,46,0
13910,190750,87,0.0,0.000000,46,0
13911,190750,9,198.0,4.066543,46,1

Aseguramos el tipo de dato:

In [107]:
# Revisamos el tipo de datos por columna 

dict(muestra.dtypes)

{'Identificador de persona': dtype('O'),
 'Identificador de hogar': dtype('int64'),
 'Area': dtype('O'),
 'Sexo': dtype('O'),
 'Edad': dtype('float64'),
 'Seguro Social - Alternativa 1': dtype('O'),
 'Seguro Social - Alternativa 2': dtype('O'),
 'Estado civil': dtype('O'),
 'Nivel de instrucción': dtype('O'),
 'Nivel de instrucción.1': dtype('O'),
 'Cómo se considera': dtype('O'),
 'Condición de inactividad': dtype('O'),
 'Categoría de ocupación': dtype('O'),
 'Cuántos años trabaja': dtype('float64'),
 'Condición de actividad': dtype('O'),
 'Ingreso Laboral': dtype('O'),
 'Grupo de Ocupación CIUO8 (población ocupada de 15 años y más)': dtype('O'),
 'Rama de Actividad CIIU4 (población ocupada de 15 años y más)': dtype('O'),
 'Ingreso per cápita': dtype('float64'),
 'Pobreza': dtype('O'),
 'Extrema Pobreza': dtype('O'),
 'Forma de tenencia de la vivienda': dtype('O'),
 'Con relación al mes anterior, la situación económica de su hogar es:': dtype('O'),
 'Cómo cree usted que será la situación económica de su hogar dentro de los próximos 3 meses:': dtype('O'),
 'Planea usted o algún miembro del hogar adquirir un vehículo en los próximos 3 meses': dtype('O'),
 'Planea usted o algún miembro del hogar adquirir un inmueble (casa, departamento, pieza) en los próximos 3 meses': dtype('O'),
 'Usted o algún miembro del hogar tiene planes de endeudamiento en los próximos 3 meses (bancos, financieras, etc.)': dtype('O'),
 'Con relación al mes anterior, la situación económica del país es:': dtype('O'),
 'Usted considera que durante los próximos 3 meses la situación económica del país será:': dtype('O'),
 'En los 3 meses anteriores, considera que la situación en Ecuador para encontrar/mejorar un puesto de trabajo es:': dtype('O'),
 'Considera usted que la situación en Ecuador para encontrar/mejorar un puesto de trabajo dentro de 3 meses será:': dtype('O'),
 'Género del jefe/a de hogar': dtype('O'),
 'Cónyuge': dtype('int64'),
 'Hijo o Hija': dtype('int64'),
 'Parientes': dtype('int64'),
 'No parientes': dtype('int64'),
 'Empleado(a) doméstico(a)': dtype('int64'),
 'Tipology': dtype('O'),
 'Ciudad': dtype('int64'),
 'Número de mujeres en el hogar': dtype('int64'),
 'Número de personas del hogar': dtype('int64')}

In [108]:
# Creamos un diccionario para modificar el tipo de datos según deseemos

NEW = {'Identificador de persona': str,
       'Identificador de hogar': str,
       'Area': str,
       'Sexo': str,
       'Edad': float,
       'Seguro Social - Alternativa 1': str,
       'Seguro Social - Alternativa 2': str,
       'Estado civil': str,
       'Nivel de instrucción': str,
       'Nivel de instrucción.1': str,
       'Cómo se considera': str,
       'Condición de inactividad': str,
       'Categoría de ocupación': str,
       'Cuántos años trabaja': float,
       'Condición de actividad': str,
       'Ingreso Laboral': str,
       'Grupo de Ocupación CIUO8 (población ocupada de 15 años y más)': str,
       'Rama de Actividad CIIU4 (población ocupada de 15 años y más)': str,
       'Ingreso per cápita': float,
       'Pobreza': str,
       'Extrema Pobreza': str,
       'Forma de tenencia de la vivienda': str,
       'Con relación al mes anterior, la situación económica de su hogar es:': str,
       'Cómo cree usted que será la situación económica de su hogar dentro de los próximos 3 meses:': str,
       'Planea usted o algún miembro del hogar adquirir un vehículo en los próximos 3 meses': str,
       'Planea usted o algún miembro del hogar adquirir un inmueble (casa, departamento, pieza) en los próximos 3 meses': str,
       'Usted o algún miembro del hogar tiene planes de endeudamiento en los próximos 3 meses (bancos, financieras, etc.)': str,
       'Con relación al mes anterior, la situación económica del país es:': str,
       'Usted considera que durante los próximos 3 meses la situación económica del país será:': str,
       'En los 3 meses anteriores, considera que la situación en Ecuador para encontrar/mejorar un puesto de trabajo es:': str,
       'Considera usted que la situación en Ecuador para encontrar/mejorar un puesto de trabajo dentro de 3 meses será:': str,
       'Género del jefe/a de hogar': str,
       'Cónyuge': int,
       'Hijo o Hija': int,
       'Parientes': int,
       'No parientes': int,
       'Empleado(a) doméstico(a)': int,
       'Tipology': str,
       'Ciudad': str,
       'Número de mujeres en el hogar': int,
       'Número de personas del hogar': int}

muestra = muestra.astype(NEW)

In [109]:
votesper.columns

Index(['PARROQUIA_CODIGO', 'Elección política', 'Votos por elección política',
       '% de electores', 'Número de personas', 'Votos proporcionales'],
      dtype='object')

# Un problema emergente
Hay un problema en cuanto a nuestro método. Vamos a ilustrarlos antes de expresarlo con jerga ténica y de forma precisa. Observemos a continuación los resultados reales para una ciduad en las elecciones del 2020:

In [110]:
votesper[votesper['PARROQUIA_CODIGO'] == '210752'].sort_values(by='% de electores', ascending=False)

,PARROQUIA_CODIGO,Elección política,Votos por elección política,% de electores,Número de personas,Votos proporcionales
21,210752,1030,355.0,29.806885,17,5
55,210752,2,206.0,17.296390,17,2
2,210752,Ausentes,140.0,11.754828,17,1
1,210752,Blancos,122.0,10.243493,17,1
0,210752,Nulos,91.0,7.640638,17,1
...,...,...,...,...,...,...
31,210752,1045,0.0,0.000000,17,0
30,210752,1043,0.0,0.000000,17,0
29,210752,1042,0.0,0.000000,17,0
28,210752,1040,0.0,0.000000,17,0
93,210752,9,0.0,0.000000,17,0

En la ciudad 80352, 653 personas votaron por la organización política (op) 47; 213 personas estuvieron ausentes; 118 obtaron por el blanco; 108, por la op 9; etc.
En nuestro método de estimación, relativizamos este número de elecciones de forma proporcional. Es decir, esos 653 votos para la op 47 son 49,97% del total de votos de la ciudad (suma de votos de todos los votos para cada elección política). Esos 49,97% votos para unoa muestra de 10 personas son 4 votos. 
## El problema
Este inconveniente surge de muestras muy pequeñas. Por ejemplo, para la misma ciudad 210752 cuando el % de electores es muy pequeño (como un 2,68% para el caso de la op 1004) los votos proporcionales de la muestra serán 0. Pero pasa lo mismo para la op 1031, 1046, 24, etc. Aquí está el problema. No es posible distuinguir elecciones electorales en una muestra como la de esta ciudad.

<center><b>% de electores demasiado pequeño y asignación del voto</b></center>

In [111]:
votesper.loc[( (votesper['PARROQUIA_CODIGO'] == '210752') & (votesper['% de electores'] < 5) & (votesper['% de electores'] != 0)), ]

,PARROQUIA_CODIGO,Elección política,Votos por elección política,% de electores,Número de personas,Votos proporcionales
6,210752,1004,32.0,2.686818,17,0
22,210752,1031,21.0,1.763224,17,0
32,210752,1046,10.0,0.839631,17,0
57,210752,24,6.0,0.503778,17,0
60,210752,29,13.0,1.091520,17,0
66,210752,42,20.0,1.679261,17,0
67,210752,44,34.0,2.854744,17,0
74,210752,61,9.0,0.755668,17,0
83,210752,75,46.0,3.862301,17,0
85,210752,78,16.0,1.343409,17,0

Al ser imposible distinguir la elección política con muestras tan pequeñas será mejor descartar estos casos. Esta es una elección adecuada debido a que nuestro método consirtirá en asignar aleatoriamente una elección política para una persona de la muestra del ENEMDU. Para ganar claridad describámoslo. <br>

# Asiganación proporcinal de voto

In [112]:
votesper.loc[( (votesper['PARROQUIA_CODIGO'] == '210752') & (votesper['Votos proporcionales'] != 0) ), ]

,PARROQUIA_CODIGO,Elección política,Votos por elección política,% de electores,Número de personas,Votos proporcionales
0,210752,Nulos,91.0,7.640638,17,1
1,210752,Blancos,122.0,10.243493,17,1
2,210752,Ausentes,140.0,11.754828,17,1
21,210752,1030,355.0,29.806885,17,5
55,210752,2,206.0,17.296390,17,2

En la misma ciudad hay 1 elección política que asiganar a una de esas 17 personas de la muestra que sea Nulos. Es decir, suponer que una persona optó por el Nulo y tomar su información en cuenta para estudiar los factores (variables de la muestra obtenida del ENEMDU) asociados a esa decisión de ausentarse. Luego hay que suponer que 2 votó blanco y hacer lo mismo. Y así sucesivamente. Hay 10 personas de 17 a las que asignarles una elección política.

El resto de personas (7) serán eliminadas de la base, pues será más peligroso estudiar sus factores asignando algún tipo de elección. Es decir, si, por ejemplo, para la ciudad 210752 elegimos una persona y suponemos que voto por la lista 1004, que se ve en la tabla **% de electores demasiado pequeño y asignación del voto**, para la que el porcentaje de Elección política es 2,68%, con 0 votos asignados, sus factores podrían ser los mismo o diferentes de una a la que asignaramos la op 1031 on un % de electores de 1,76%. Así, será mejor depurar 7 personas de la base para la simulación. En código sería lo siguiente:

<center><b>Base depurada</b></center>

In [113]:
votesper[votesper['Votos proporcionales'] != 0]

,PARROQUIA_CODIGO,Elección política,Votos por elección política,% de electores,Número de personas,Votos proporcionales
0,210752,Nulos,91.0,7.640638,17,1
1,210752,Blancos,122.0,10.243493,17,1
2,210752,Ausentes,140.0,11.754828,17,1
21,210752,1030,355.0,29.806885,17,5
55,210752,2,206.0,17.296390,17,2
...,...,...,...,...,...,...
13839,190750,1030,403.0,8.276854,46,3
13840,190750,1031,599.0,12.302321,46,5
13872,190750,18,175.0,3.594167,46,1
13901,190750,75,167.0,3.429862,46,1
13911,190750,9,198.0,4.066543,46,1

# Base para la simulación

Bueno, llegados a este punto vamos a usar solo 3 columnas: Ciudad, Elección electoral y Votos para la muestra.

In [114]:
v = votesper[votesper['Votos proporcionales'] != 0][['PARROQUIA_CODIGO', 
                                                     'Elección política', 
                                                     'Votos proporcionales']]
v

      PARROQUIA_CODIGO Elección política  Votos proporcionales
0               210752             Nulos                     1
1               210752           Blancos                     1
2               210752          Ausentes                     1
21              210752              1030                     5
55              210752                 2                     2
...                ...               ...                   ...
13839           190750              1030                     3
13840           190750              1031                     5
13872           190750                18                     1
13901           190750                75                     1
13911           190750                 9                     1

[1037 rows x 3 columns]

In [115]:
v = v.groupby(by=['PARROQUIA_CODIGO']).size().reset_index(name='Número de personas')
v

    PARROQUIA_CODIGO  Número de personas
0             100152                   6
1             100157                  10
2             100250                   8
3             100254                   7
4             100453                   5
..               ...                 ...
143           230157                   6
144           240152                  11
145           240156                  10
146           240250                  12
147           240350                   9

[148 rows x 2 columns]

Para seleccionar muestras de tamañao n, vamos a inspirarnos en el código de la respuesta 5 del siguiente *stackoverflow* https://stackoverflow.com/questions/22472213/python-random-selection-per-group.

Como ejemplo seleccionemos una sola persona por cada ciudad:

In [116]:
# Solo un ajuste antes:

muestra.rename(columns={'Ciudad': 'PARROQUIA_CODIGO'}, inplace=True)

# Seleccionar solo una persona de muestra

n = 1
muestra.groupby(by=['PARROQUIA_CODIGO']).apply(lambda x: x.sample(min(n,len(x)))).reset_index(drop=True)

,Identificador de persona,Identificador de hogar,Area,Sexo,Edad,Seguro Social - Alternativa 1,Seguro Social - Alternativa 2,Estado civil,Nivel de instrucción,Nivel de instrucción.1,...,Género del jefe/a de hogar,Cónyuge,Hijo o Hija,Parientes,No parientes,Empleado(a) doméstico(a),Tipology,PARROQUIA_CODIGO,Número de mujeres en el hogar,Número de personas del hogar
0,10015000550200902101,100150005502009021,Urbana,Mujer,36.0,Ninguno,Ninguno,Divorciado(a),Primaria,Educación Básica,...,Mujer,0,3,0,0,0,Hogar tipo 5,100150,2,4
1,10015290090200504103,100152900902005041,Rural,Hombre,19.0,Ninguno,Ninguno,Soltero(a),Educación Media,Educación Media/Bachillerato,...,Hombre,1,2,1,1,0,Hogar tipo 16,100152,3,5
2,10015300020100901102,100153000201009011,Rural,Hombre,52.0,Ninguno,Ninguno,Separado(a),Primaria,Educación Básica,...,Mujer,0,1,0,0,0,Hogar tipo 5,100153,1,2
3,10015790080100505105,100157900801005051,Rural,Mujer,16.0,"IESS, seguro general",Ninguno,Soltero(a),Educación Básica,Educación Básica,...,Hombre,1,4,2,1,0,Hogar tipo 16,100157,4,8
4,10025000080300901102,100250000803009011,Urbana,Hombre,43.0,Ninguno,Ninguno,Unión libre,Primaria,Educación Básica,...,Mujer,1,1,2,2,0,Hogar tipo 16,100250,2,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,09215000510100907101,92150005101009071,Urbana,Hombre,52.0,Ninguno,Ninguno,Unión libre,Primaria,Educación Básica,...,Hombre,1,1,0,1,0,Hogar tipo 10,92150,2,3
362,09225090020200505108,92250900202005051,Rural,Hombre,28.0,Ninguno,Ninguno,Unión libre,Secundaria,Educación Media/Bachillerato,...,Hombre,1,5,3,1,0,Hogar tipo 16,92250,6,10
363,09225190120200502102,92251901202005021,Rural,Mujer,75.0,Ninguno,Ninguno,Casado(a),Secundaria,Educación Media/Bachillerato,...,Hombre,1,0,0,1,0,Hogar tipo 11,92251,1,2
364,09235000050200502101,92350000502005021,Urbana,Hombre,48.0,"IESS, seguro general",Ninguno,Casado(a),Secundaria,Educación Media/Bachillerato,...,Hombre,1,3,1,1,0,Hogar tipo 16,92350,4,6
365,09275000070200901102,92750000702009011,Urbana,Mujer,34.0,Ninguno,Ninguno,Unión libre,Superior Universitario,Superior,...,Hombre,1,3,0,1,0,Hogar tipo 10,92750,3,5

Ahoa especifiquemos el tamaño de la muestra:

## Algortimo para seleccionar submuestras especificadas de tamaño n y obtener una base para la simulación

**Descripcción**: 

Vamos a filtrar la base *muestra*, obteniendo submuestras para cada ciudad. <br>
Lo que deseamos es que en cada ciudad se elija un número de persona especificadas en la columna *Número de personas a seleccionar* de la tabla *v* aleatoriamente (v['Número de personas a seleccionar']). <br>
Para cada submuestra de ciudad vamos a elegir un número n de persona aleatoriamente.
Vamos a hacer esto 91 veces, ya que hay 91 ciudades. Esta selección significa tomar un número n de personas con  muestra.shape[1] (41) valores de variables.
Finalmente, vamos a juntar estas submustras obtenidas de la selección de el número n de personas en una base llamada df_simulation.

In [117]:
limit = v.shape[0] # Número indicador de filas apra usar en el bucle
Frames = [] # Submuestras a concatenar en una sola base

for i in range(limit):
    df_PARROQUIA_CODIGO = muestra[muestra['PARROQUIA_CODIGO'] == v['PARROQUIA_CODIGO'][i]]
    select = v['Número de personas'][i]
    frame = df_PARROQUIA_CODIGO.groupby(by=['PARROQUIA_CODIGO']).apply(lambda x: x.sample(min(select,len(x)))).reset_index(drop=True)
    Frames.append(frame)

df_simulation = pd.concat(Frames)
df_simulation

,Identificador de persona,Identificador de hogar,Area,Sexo,Edad,Seguro Social - Alternativa 1,Seguro Social - Alternativa 2,Estado civil,Nivel de instrucción,Nivel de instrucción.1,...,Género del jefe/a de hogar,Cónyuge,Hijo o Hija,Parientes,No parientes,Empleado(a) doméstico(a),Tipology,PARROQUIA_CODIGO,Número de mujeres en el hogar,Número de personas del hogar
0,10015290090200507101,100152900902005071,Rural,Mujer,74.0,"IESS, seguro general",Ninguno,Separado(a),Primaria,Educación Básica,...,Mujer,0,0,0,0,0,Hogar tipo 1,100152,1,1
1,10015290090200503101,100152900902005031,Rural,Hombre,63.0,Ninguno,Ninguno,Casado(a),Primaria,Educación Básica,...,Hombre,1,0,0,1,0,Hogar tipo 11,100152,1,2
2,10015290090200504102,100152900902005041,Rural,Mujer,40.0,Ninguno,Ninguno,Casado(a),Primaria,Educación Básica,...,Hombre,1,2,1,1,0,Hogar tipo 16,100152,3,5
3,10015290090200501102,100152900902005011,Rural,Mujer,69.0,Ninguno,Ninguno,Casado(a),Ninguno,Ninguno,...,Hombre,1,0,0,1,0,Hogar tipo 11,100152,1,2
4,10015290090200501101,100152900902005011,Rural,Hombre,76.0,Ninguno,Ninguno,Casado(a),Ninguno,Ninguno,...,Hombre,1,0,0,1,0,Hogar tipo 11,100152,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,24035000140600502105,240350001406005021,Urbana,Mujer,20.0,Ninguno,Ninguno,Soltero(a),Superior Universitario,Superior,...,Hombre,1,1,2,1,0,Hogar tipo 16,240350,4,5
5,24035000140600502103,240350001406005021,Urbana,Mujer,57.0,"IESS, seguro general",Ninguno,Separado(a),Superior Universitario,Superior,...,Hombre,1,1,2,1,0,Hogar tipo 16,240350,4,5
6,24035000140600504105,240350001406005041,Urbana,Hombre,27.0,Ninguno,Ninguno,Soltero(a),Secundaria,Educación Media/Bachillerato,...,Hombre,1,4,0,1,0,Hogar tipo 10,240350,2,6
7,24035000140600504101,240350001406005041,Urbana,Hombre,59.0,Ninguno,Ninguno,Casado(a),Educación Básica,Educación Básica,...,Hombre,1,4,0,1,0,Hogar tipo 10,240350,2,6
8,24035000140600501102,240350001406005011,Urbana,Mujer,32.0,Ninguno,Ninguno,Casado(a),Secundaria,Educación Media/Bachillerato,...,Hombre,1,3,0,1,0,Hogar tipo 10,240350,3,5

Será importante verificar que lo que hemos hecho no contenga errores. Para asegurarnos vamos a contar el número de persona que hay en cada submuestra. La siguiente tabla debería ser equivalente a la tabla *v*.

<center><b>Verificación de personas seleccionadas del ENEMDU por parroquia</b></center>

In [118]:
df_simulation.groupby(by=['PARROQUIA_CODIGO'])['Identificador de persona'].size().reset_index(name='Número de personas seleccionadas')

    PARROQUIA_CODIGO  Número de personas seleccionadas
0             100152                                 6
1             100157                                10
2             100250                                 8
3             100254                                 7
4             100453                                 5
..               ...                               ...
143           230157                                 6
144           240152                                11
145           240156                                10
146           240250                                12
147           240350                                 9

[148 rows x 2 columns]

Una vez verificado podemos proceder a asignar una elección política aleatoriamente a cada persona de una ciudad.

#### AAG2

In [119]:
r = votesper[votesper['Votos proporcionales'] != 0][['PARROQUIA_CODIGO', 'Elección política', 'Votos proporcionales']]
r.shape

(1037, 3)

In [120]:
lim = r.shape[0]
FRAMES = []

for ner in range(lim):
    row = r.values[ner] # selecciona la fila para repetir el número de veces indicado
    n_repit = r['Votos proporcionales'].values[ner] # selecciona el número de veces indicado
    sigma = np.repeat([r.values[ner]], [n_repit], axis=0)
    k = pd.DataFrame(sigma) # Creo un DataFrame
    FRAMES.append(k) # Agrego el df para concatenarlo luego

df_s = pd.concat(FRAMES)
df_s.rename(columns={0: 'PARROQUIA_CODIGO', 1: 'Elección política', 2: 'Votos proporcionales'}, inplace=True)
df_s

   PARROQUIA_CODIGO Elección política Votos proporcionales
0            210752             Nulos                    1
0            210752           Blancos                    1
0            210752          Ausentes                    1
0            210752              1030                    5
1            210752              1030                    5
..              ...               ...                  ...
3            190750              1031                    5
4            190750              1031                    5
0            190750                18                    1
0            190750                75                    1
0            190750                 9                    1

[3702 rows x 3 columns]

### Verifiación
Lo que hemos hecho debería haber repetido la elección política el número de veces el número de votos proporcionales, vamos a crear un conteo de esa repetición que llamaremos *n*.

In [121]:
df_s.groupby(by=['PARROQUIA_CODIGO', 'Elección política']).size().reset_index(name='n').sort_values(['PARROQUIA_CODIGO', 'Elección política'])

     PARROQUIA_CODIGO Elección política  n
0              100152              1030  3
1              100152                18  1
2              100152                 2  2
3              100152          Ausentes  3
4              100152           Blancos  2
...               ...               ... ..
1032           240350                42  1
1033           240350                84  3
1034           240350          Ausentes  4
1035           240350           Blancos  1
1036           240350             Nulos  2

[1037 rows x 3 columns]

*n* deberá ser igual a lso votos proporcionales para cada parroquia y elección política.

In [122]:
r.sort_values(['PARROQUIA_CODIGO', 'Elección política'])

     PARROQUIA_CODIGO Elección política  Votos proporcionales
303            100152              1030                     3
336            100152                18                     1
337            100152                 2                     2
284            100152          Ausentes                     3
283            100152           Blancos                     2
...               ...               ...                   ...
9842           240350                42                     1
9866           240350                84                     3
9778           240350          Ausentes                     4
9777           240350           Blancos                     1
9776           240350             Nulos                     2

[1037 rows x 3 columns]

Una vez verificado, procedemos a emparejar las bases:

In [123]:
r['random'] = np.random.randint(0, 20, r.shape[0])
Ya = r.sort_values(by=['PARROQUIA_CODIGO', 'Elección política', 'random'])
Ya

     PARROQUIA_CODIGO Elección política  Votos proporcionales  random
303            100152              1030                     3       5
336            100152                18                     1       6
337            100152                 2                     2      12
284            100152          Ausentes                     3       9
283            100152           Blancos                     2       3
...               ...               ...                   ...     ...
9842           240350                42                     1      16
9866           240350                84                     3       2
9778           240350          Ausentes                     4      17
9777           240350           Blancos                     1      19
9776           240350             Nulos                     2       2

[1037 rows x 4 columns]

# Finalmente tenemos la muestra para nuestro análisis.

In [124]:
df_regresion = df_simulation.merge(Ya, on=['PARROQUIA_CODIGO'])

In [127]:
df_regresion.columns

Index(['Identificador de persona', 'Identificador de hogar', 'Area', 'Sexo',
       'Edad', 'Seguro Social - Alternativa 1',
       'Seguro Social - Alternativa 2', 'Estado civil', 'Nivel de instrucción',
       'Nivel de instrucción.1', 'Cómo se considera',
       'Condición de inactividad', 'Categoría de ocupación',
       'Cuántos años trabaja', 'Condición de actividad', 'Ingreso Laboral',
       'Grupo de Ocupación CIUO8 (población ocupada de 15 años y más)',
       'Rama de Actividad CIIU4 (población ocupada de 15 años y más)',
       'Ingreso per cápita', 'Pobreza', 'Extrema Pobreza',
       'Forma de tenencia de la vivienda',
       'Con relación al mes anterior, la situación económica de su hogar es:',
       'Cómo cree usted que será la situación económica de su hogar dentro de los próximos 3 meses:',
       'Planea usted o algún miembro del hogar adquirir un vehículo en los próximos 3 meses',
       'Planea usted o algún miembro del hogar adquirir un inmueble (casa, departamento, pieza) en los próximos 3 meses',
       'Usted o algún miembro del hogar tiene planes de endeudamiento en los próximos 3 meses (bancos, financieras, etc.)',
       'Con relación al mes anterior, la situación económica del país es:',
       'Usted considera que durante los próximos 3 meses la situación económica del país será:',
       'En los 3 meses anteriores, considera que la situación en Ecuador para encontrar/mejorar un puesto de trabajo es:',
       'Considera usted que la situación en Ecuador para encontrar/mejorar un puesto de trabajo dentro de 3 meses será:',
       'Género del jefe/a de hogar', 'Cónyuge', 'Hijo o Hija', 'Parientes',
       'No parientes', 'Empleado(a) doméstico(a)', 'Tipology',
       'PARROQUIA_CODIGO', 'Número de mujeres en el hogar',
       'Número de personas del hogar', 'Elección política',
       'Votos proporcionales', 'random'],
      dtype='object')

In [125]:
df_regresion.to_csv('Data/df_regresion.csv', index_label=False, encoding='utf-8')